version: '3.4'

services:
  catalogdb:
    image: mongo

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Servcies/Catalog/CatalogAPI/Dockerfile
  

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Servcies/Basket/Basket.API/Dockerfile

volumes:
  mongo_data: 
