version: '3.4'

services:
  catalogdb:
    image: mongo

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Servcies/Catalog/CatalogAPI/Dockerfile
  

volumes:
  mongo_data: 